#!/usr/bin/env node
/**
 * agentready batch — scan a list of domains, emit a ranked leaderboard.
 * Zero dependencies. Usage: node batch.mjs <list.txt> [--out <dir>] [--cat "Calgary plumbers"]
 * list.txt = one URL/domain per line; blank lines and #comments ignored.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';

const args = process.argv.slice(2);
const listFile = args.find((a) => !a.startsWith('--'));
const outIdx = args.indexOf('--out');
const outDir = outIdx !== -1 ? args[outIdx + 1] : join(process.cwd(), 'agentready-out');
const catIdx = args.indexOf('--cat');
const category = catIdx !== -1 ? args[catIdx + 1] : 'the cohort';

const lines = readFileSync(listFile, 'utf8')
  .split('\n').map((l) => l.trim())
  .filter((l) => l && !l.startsWith('#'));

mkdirSync(outDir, { recursive: true });
const rows = [];

for (const target of lines) {
  let r;
  try {
    const raw = execFileSync(process.execPath, [join(import.meta.dirname, 'scan.mjs'), target, '--json', '--out', outDir], { encoding: 'utf8', maxBuffer: 8 * 1024 * 1024 });
    r = JSON.parse(raw.slice(raw.indexOf('{'), raw.lastIndexOf('}') + 1));
  } catch (e) {
    console.error(`  ! ${target} — ${String(e.message).slice(0, 120)}`);
    rows.push({ host: target, score: null, grade: '?', unreachable: true });
    continue;
  }
  rows.push({
    host: r.host, target: r.target, score: r.score, grade: r.grade,
    gaps: r.gaps.slice(0, 3).map((g) => g.name), topGapPts: r.gaps[0]?.weight || 0,
    pts: `${r.earned}/${r.totalWeight}`, llms: r.checks.find((c) => c.id === 'llms_txt')?.pass,
    jsonld: r.checks.find((c) => c.id === 'jsonld')?.pass,
    ms: r.homeMs,
  });
  console.log(`  ${String(r.score).padStart(3)}/100  ${r.grade}  ${r.host}`);
}

const live = rows.filter((r) => r.score !== null).sort((a, b) => b.score - a.score);
const mean = live.length ? (live.reduce((s, r) => s + r.score, 0) / live.length).toFixed(1) : 'n/a';
const withLlms = live.filter((r) => r.llms).length;
const withJsonld = live.filter((r) => r.jsonld).length;
const isoDate = new Date().toISOString().slice(0, 10);

const esc = (s) => String(s).replace(/[<>&"]/g, (m) => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;' }[m]));
const rowsHtml = live.map((r, i) => `
    <tr>
      <td class="rank">${i + 1}</td>
      <td class="host">${esc(r.host)}</td>
      <td class="score ${r.score >= 62 ? 'good' : r.score >= 25 ? 'mid' : 'bad'}">${r.score}</td>
      <td class="grade">${r.grade}</td>
      <td class="flag">${r.llms ? '&#10003;' : '&#10007;'}</td>
      <td class="flag">${r.jsonld ? '&#10003;' : '&#10007;'}</td>
      <td class="gaps">${esc(r.gaps.join(' · ')) || '—'}</td>
    </tr>`).join('');

const html = `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI Agent Readiness — ${esc(category)} (${isoDate})</title>
<style>
  :root{--bg:#0b0d12;--card:#141821;--line:#232838;--fg:#e8ecf4;--mut:#8b95ab;--good:#3ddc84;--mid:#ffc857;--bad:#ff5c7a}
  *{box-sizing:border-box}
  body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Inter,sans-serif;padding:40px 20px}
  .wrap{max-width:980px;margin:0 auto}
  h1{font-size:22px;margin:0 0 6px}
  .sub{color:var(--mut);font-size:13px;margin-bottom:24px}
  .stats{display:flex;gap:14px;flex-wrap:wrap;margin-bottom:24px}
  .stat{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:14px 18px;min-width:150px}
  .stat b{display:block;font-size:26px;line-height:1.1}
  .stat span{color:var(--mut);font-size:11px;letter-spacing:.07em;text-transform:uppercase}
  table{width:100%;border-collapse:collapse;background:var(--card);border:1px solid var(--line);border-radius:14px;overflow:hidden;font-size:14px}
  th,td{text-align:left;padding:10px 14px;border-bottom:1px solid var(--line)}
  th{font-size:11px;letter-spacing:.07em;text-transform:uppercase;color:var(--mut)}
  tr:last-child td{border-bottom:none}
  .rank{width:34px;color:var(--mut)}
  .score{font-weight:700;font-variant-numeric:tabular-nums;width:52px}
  .score.good{color:var(--good)} .score.mid{color:var(--mid)} .score.bad{color:var(--bad)}
  .grade{width:40px;color:var(--mut)}
  .flag{width:34px;text-align:center;color:var(--mut)}
  .gaps{color:var(--mut);font-size:12px}
  .host{font-weight:600}
  .foot{margin-top:20px;color:var(--mut);font-size:12px}
</style></head><body><div class="wrap">
  <h1>AI Agent Readiness — ${esc(category)}</h1>
  <div class="sub">${live.length} sites scanned · ${isoDate} · 15 machine-readability checks · generated by agentready</div>
  <div class="stats">
    <div class="stat"><b>${mean}</b><span>mean score /100</span></div>
    <div class="stat"><b>${live.filter((r) => r.score >= 62).length}/${live.length}</b><span>grade C or better</span></div>
    <div class="stat"><b>${withLlms}/${live.length}</b><span>publish llms.txt</span></div>
    <div class="stat"><b>${withJsonld}/${live.length}</b><span>have structured data</span></div>
  </div>
  <table><thead><tr><th></th><th>Site</th><th>Score</th><th>Gr</th><th>llms</th><th>ld+json</th><th>Top gaps</th></tr></thead>
  <tbody>${rowsHtml}</tbody></table>
  <div class="foot">Checked: llms.txt · llms-full.txt · ai.txt · AI crawler rules · sitemap · JSON-LD · schema types · OpenAPI · MCP manifest · markdown negotiation · security.txt · OpenGraph meta · agent hint files</div>
</div></body></html>`;

writeFileSync(join(outDir, 'leaderboard.html'), html);
writeFileSync(join(outDir, 'leaderboard.csv'),
  'rank,host,score,grade,earned,total,llms_txt,json_ld,top_gap,response_ms\n' +
  live.map((r, i) => [i + 1, r.host, r.score, r.grade, ...r.pts.split('/'), r.llms ? 1 : 0, r.jsonld ? 1 : 0, `"${r.gaps[0] || ''}"`, r.ms].join(',')).join('\n') + '\n');

console.log(`\n  mean ${mean}/100 · ${live.length} live · wrote ${join(outDir, 'leaderboard.html')}`);
